# what is the goal of this workflows - whenever someone change the python code, linter will check at that time.
name: Auto linter

on:
  push:
    paths: "*.py"

jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout/ clone the code
        uses: actions/checkout@v7 
      - name: Installer Linter 
        run: pip install ruff
    
